[package]
name = "halo2-merkle"
version = "0.1.0"
edition = "2018"

[dependencies]
ff = "0.9"
halo2 = { git = "https://github.com/zcash/halo2", branch = "main" }
lazy_static = "1.4.0"
rand = "0.8"
rand_chacha = "0.3.0"
